version: "3"
services: 
  app:
    build: ./app/
    image: my-ml-service-api:latest 
    env_file:
    - .env
    volumes:
      - ./app:/app

      
  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app


  rabbitmq:
    image: rabbitmq:4.0.7 
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    restart: on-failure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data/ 
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648  
    depends_on:
      - app    


  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    #ports:
    #- 5432:5432
    expose:
      - 5432
 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 


volumes:
    postgres_data:
    rabbitmq_data: