version: "3"
services: 
  app:
    build: ./app/
    image: my-ml-service-api:latest 
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app

      
  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app


  rabbitmq:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq  
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648  
    depends_on:
      - app    


  db:
    image: postgres
    restart: always
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ../2. Init Database:/docker-entrypoint-initdb.d

    environment:
      #POSTGRES_DB: "db"
      #POSTGRES_USER: "user"
      POSTGRES_PASSWORD: example
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 